[package]
name = "transfer-back"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
smart-contract = { path = "../.." }
serde = "1"
serde_derive = "1"
