[package]
name = "token"
version = "0.1.0"
authors = ["Kenta Iwasaki <kenta@perlin.net>"]
edition = "2018"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
smart_contract = { path = "../.." }
smart_contract_macro = { path = "../../smart-contract-macro"}