[package]
name = "lucky-draw"
version = "0.1.0"
authors = ["Abby <abbychau@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
smart-contract = { path = "../../smart-contract" }
smart-contract-macros = { path = "../../smart-contract-macros"}
