[package]
name = "smart_contract_macro"
version = "0.1.0"
authors = ["Kenta Iwasaki <kenta@perlin.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.9"
proc-macro2 = "0.4.24"

[dependencies.syn]
version = "0.15.26"
features = ["full", "visit"]